// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szqoezlkwrpcxapqfdvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6cW9lemxrd3JwY3hhcHFmZHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDI1MzEsImV4cCI6MjA2NTQ3ODUzMX0.ptZU5MQ_8rjGDKfQ4ncFKhDxnBVFKlylYZ7trWIOWWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);